Fix halo again
DifferentiableUniverseInitiative/jaxDecomp pull request #23
Opened 2024-07-05 10:48 UTC by ASKabalan

This PR comes after this one https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/19
Instead of allocating using `mlir.full_like_aval` I allocate using `cudecompMalloc` but I keep a fallback to XLA if needed using `JD_ALLOCATE_WITH_XLA=1`

2024-07-08 22:03 UTC, aboucaud commented
Out of my league..

2024-07-08 23:20 UTC, ASKabalan commented
Still much simpler than JAX distributed :smiling_face_with_tear:

2024-07-09 18:40 UTC, EiffL commented
Hum... but I don't understand what was the issue here, as long as the workspace is created by XLA in each call the primitive and that the primitive uses the provided workspace in the input stream, what goes wrong?

2024-07-09 19:04 UTC, ASKabalan commented
The workspace is not created at each call.
It is only created at the lowering phase as ir.constants

If I do an LPT it is fine.
If I do a nbody sim with a mesh size of 256 it is also fine (on a V100 32G)
512 and above I get a deadlock, with some further inspection it apeared to me that there is an illegal access of memory by some of the processes (which caused the deadlock)

I inspected the memory and found :

```
Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 0
Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 1
Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 2

Calling cudecompUpdateHalosX : 0x151003004300 On axis 0
Calling cudecompUpdateHalosX : 0x151003004300 On axis 1
Calling cudecompUpdateHalosX : 0x151003004300 On axis 2
```

XLA changes the memory address which should not happen (again the lowering happends only once)
This means that the memory have been repurposed.

Using `cudecompmalloc` this does not happend.

You can still reproduce if you get a 512 or 1024 on no more than 4 GPUs with the flag `JD_ALLOCATE_WITH_XLA`

2024-07-09 19:06 UTC, ASKabalan commented
To get the error to show, you need to remove all `block_until_ready() `statements

2024-07-09 19:26 UTC, EiffL commented
Hum, but the thing that worries me is that the same could happen for the
other ops no?
And I don't see why the memory provided in the stream to the kernel would
not be ok.

On Tue, Jul 9, 2024, 3:04 PM Wassim KABALAN ***@***.***>
wrote:

> The workspace is not created at each call.
> It is only created at the lowering phase as ir.constants
>
> If I do an LPT it is fine.
> If I do a nbody sim with a mesh size of 256 it is also fine (on a V100 32G)
> 512 and above I get a deadlock, with some further inspection it apeared to
> me that there is an illegal access of memory by some of the processes
> (which caused the deadlock)
>
> I inspected the memory and found :
>
> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 0
> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 1
> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 2
>
> Calling cudecompUpdateHalosX : 0x151003004300 On axis 0
> Calling cudecompUpdateHalosX : 0x151003004300 On axis 1
> Calling cudecompUpdateHalosX : 0x151003004300 On axis 2
>
> XLA changes the memory address which should not happen (again the lowering
> happends only once)
> This means that the memory have been repurposed.
>
> Using cudecompmalloc this does not happend.
>
> You can still reproduce if you get a 512 or 1024 on no more than 4 GPUs
> with the flag JD_ALLOCATE_WITH_XLA
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/23#issuecomment-2218440396>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGSLFZYSND6GGANMNAAPADZLQX43AVCNFSM6AAAAABKM7FAX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMJYGQ2DAMZZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-07-09 19:27 UTC, EiffL commented
Are you sure it's not something different like not having the right size of
workspace? Maybe we have a different meaning for halo size

On Tue, Jul 9, 2024, 3:25 PM Eiffel ***@***.***> wrote:

> Hum, but the thing that worries me is that the same could happen for the
> other ops no?
> And I don't see why the memory provided in the stream to the kernel would
> not be ok.
>
> On Tue, Jul 9, 2024, 3:04 PM Wassim KABALAN ***@***.***>
> wrote:
>
>> The workspace is not created at each call.
>> It is only created at the lowering phase as ir.constants
>>
>> If I do an LPT it is fine.
>> If I do a nbody sim with a mesh size of 256 it is also fine (on a V100
>> 32G)
>> 512 and above I get a deadlock, with some further inspection it apeared
>> to me that there is an illegal access of memory by some of the processes
>> (which caused the deadlock)
>>
>> I inspected the memory and found :
>>
>> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 0
>> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 1
>> Calling cudecompUpdateHalosX : 0x14a75f004300 On axis 2
>>
>> Calling cudecompUpdateHalosX : 0x151003004300 On axis 0
>> Calling cudecompUpdateHalosX : 0x151003004300 On axis 1
>> Calling cudecompUpdateHalosX : 0x151003004300 On axis 2
>>
>> XLA changes the memory address which should not happen (again the
>> lowering happends only once)
>> This means that the memory have been repurposed.
>>
>> Using cudecompmalloc this does not happend.
>>
>> You can still reproduce if you get a 512 or 1024 on no more than 4 GPUs
>> with the flag JD_ALLOCATE_WITH_XLA
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/23#issuecomment-2218440396>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAGSLFZYSND6GGANMNAAPADZLQX43AVCNFSM6AAAAABKM7FAX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMJYGQ2DAMZZGY>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***
>> com>
>>
>

2024-07-09 19:40 UTC, ASKabalan commented
I am going to try to reproduce and tell you.
But the halo_extent here is half of the halo size but what I see is there is enough space
The size of the input is mesh + half of the halo and the other half is the extent

this should be enough

For the FFT, the allocation is handled by us and not cufft because we use [cufftsetautoallocation](https://docs.nvidia.com/cuda/cufft/#cufftsetautoallocation) and the work is shared for the FFT and Transpose

The only difference I see is that the FFT is inplace (it uses some temporary parameters but nothing dangerous)
The transpositions are inplace aswell

The supplement memory required by a halo exchange is more?
Anyway it cannot be anything else, since when I use `cudecomp` the illegal access is not reproduced

2024-07-19 14:24 UTC, EiffL commented on jaxdecomp/_src/halo.py
> +    if os.environ.get("JD_ALLOCATE_WITH_XLA", "0") == "0":
can we remove this entire mechanism?

2024-07-19 14:25 UTC, EiffL commented on src/halo.cu
> +  m_WorkSize = dtype_size * workspace_num_elements;
let's remove this

2024-07-19 14:31 UTC, EiffL commented
I think it's better to let XLA handle memory, because it can decide to free it when not necessary.

2024-07-19 14:39 UTC, EiffL requested changes
We should remove the cuda memory allocation thing for halos, better to be consistent in memory handling throughout

2024-07-19 14:49 UTC, ASKabalan commented
I just tested.
It is ok for me.
Can I merge?

2024-07-19 16:36 UTC, merged